# HatCosmetics config version: 3
# For both my sake and yours, please DO NOT change the config version!

# Refer to Spigot-API Materials for list of items: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Item used for all hats:
item: FEATHER
# Item used to border the hats in the GUI:
border: LIGHT_BLUE_STAINED_GLASS_PANE

# The number of hat rows in the GUI (must be between 1 and 4)
# This is only for the actual hats and not the two rows for the border and close menu item
gui_rows: 1

hats:
  # This is where you add your hats
  staffHat:             # The name used for /hats equip and the hat's permission
    #item: DIAMOND_HOE  # (OPTIONAL) Only use if your hat uses a different item from the rest
    data: 1000101       # The custom model data defined in your resource pack for the item
    name: "&fStaff Hat" # The name displayed on the item
    #description:       # (OPTIONAL) Adds list of text underneath the "Hat Cosmetic" line
    #  - ""
    #  - "&bShow who's boss!"