main: me.Tonus_.hatCosmetics.Main
name: HatCosmetics
version: 1.0.0
author: Tonus_
api-version: 1.14

commands:
  hatCosmetics:
    description: Primary command for hats.
    aliases: [hats]

permissions:
  hatcosmetics.reload:
    description: Allows you to reload the plugin's config.
    default: op
  hatcosmetics.hat:
    description: Allows use of hat in permission.
    default: op